### ISSUE TITLE
Shared state between processes ?

### ISSUE THREAD

**Issue by IfnotFr** [dulnan/nuxt-multi-cache#5]
Hi,

Today I am facing a problem on my production environment.

Each day I purge the yesterday cache using `/__nuxt_multi_cache/purge/all` but it looks when we are using `pm2` with multiple processes the cache state is not shared : some of my nuxt processes have the cache gone, some not.

Is the cache state is shared between processes on production or specific to a process ?

Thanks.

**Comment by dulnan** [comment]
The cache is specific to a process, since it's using https://www.npmjs.com/package/lru-cache as the cache backend (memory). That means this module currently does not support multiple processes, since it is not stateless. But that is something that should absolutely be supported.

I think the best approach would be to allow passing a custom cache implementation (with get, set, purge methods) to the module via configuration. Then module users can connect any cache backend (e.g. Redis) they like, which would work across multiple processes.

**Comment by IfnotFr** [comment]
Can't wait for this update, your module is awesome and do the work perfecly. It will be awesome with this feature to be production ready :)

**Comment by dulnan** [comment]
I worked on V2 of the module the past days (a complete rewrite), which now includes the possibility to use any cache backend and therefore have a shared state between multiple Nuxt instances.
It only supports Nuxt 3, but exclusively uses libraries that already come with Nuxt. For example unstorage, where you can use Redis or implement your own cache backend driver.

Currently released it as a beta on npm but will do a full 2.0.0 release next week.

Do you plan to continue on Nuxt 2 with the project you mentioned? I use this module myself on half a dozen projects, but the plan is to migrate these during 2023 to Nuxt 3, so I see 1.x of nuxt-multi-cache more in maintenance mode at this point.
It would be technically possible to integrate unstorage into 1.x, but it would be a breaking change. I'm just wondering if it's worth the effort.

Happy new year!

**Comment by IfnotFr** [comment]
Hi ! And thanks for the heads-up !

I actually use this plugin on my main nuxt 2 project https://playtv.fr/ (french tv catalog) I dont plan a nuxt 3 migration at the moment as the website is few month year old.

Actually for fixing the lack of shared state I purge the cache by spamming purge methods and restart the main thread durning the night cron update ^^"

On your opinion (specially if you have so many projects) is nuxt 3 migration a big thing ?

Happy new year too :)

**Comment by dulnan** [comment]
Okay, spamming purge requests is one way to solve the problem :D 

Will have a look next week and see how feasible it is to replace lru-cache with unstorage. I have already written a wrapper around lru-cache, so it should be possible. And even make it so that it doesn‘t break existing setups.

Regarding the Nuxt 3 migrations: I have only migrated one project so far, it went quite okay and took only a day. But it was a fairly small project that only started a few weeks prior with Nuxt 2. But it really depends on the specifics of the project. If you have a lot of Vuex modules for example, then you‘ll be refactoring a lot. Or if you have a lot of custom plugins, server middlewares, etc.

One Nuxt 2 project I co-maintain is the frontend for zuerich.com. We have around 300 components, tons of custom APIs, modules and plugins. It serves thousands of pages from a CMS and has a lot of custom code all over. I estimate it will take me at least 4 weeks fulltime work to migrate everything.

But working with Nuxt 3 is so refreshing. It takes a bit getting used to, but once you get the hang of it it‘s so much easier to do things, compared to Nuxt 2.

**Comment by IfnotFr** [comment]
Awesome, thank you for taking the time. I appreciate your availability for resolving your community issues.

It's interesting for nuxt3, I will definitely check this for my new projects :) I remember that for the beginning of playtv.fr I was using Vuetify and Nuxt 3 was not supported yet.

Have a nice day, and thanks again :)
