### ISSUE TITLE
Serve stale option

### ISSUE THREAD

**Issue by bennet-esyoil** [dulnan/nuxt-multi-cache#54]
Hi, 

It would be great to have a "serve stale" option, where - one might have guessed it - the cached item get's served but then refreshed in the background. We're using this package with quite a low TTL but still want to receive the stale data for performance reasons.

Let me know if there's anything I can help with :)

**Comment by dulnan** [comment]
Interesting idea! I'm thinking of ways how this could be implemented. Currently the module directly interacts with unstorage in all ways, e.g. by calling `cache.clear()` on the storage when purging a cache or by checking the maxAge when serving a cached route. Here it's very hard to render the page in the background: If the cached page is stale, the code can only decide between either returning the stale page and then finishing the request or re-rendering the page, storing the updated cache item and finishing the request.

The module would have to introduce some kind of "state" that keeps track of whether a page is already being "rendered" currently and would then serve stale pages to subsequent requests, until the first request finishes. However I'm not sure if the performance benefits would be really that huge. Also this state would have to be implemented via unstorage, to make it available across multiple instances. I fear this might actually introduce more overhead than it would improve performance.

Something else I could imagine is to serve stale pages when rendering of the page has failed, for example when a backend is down. However I'm not sure if this is easily possible with Nuxt/Nitro. I have created an issue for this here: https://github.com/dulnan/nuxt-multi-cache/issues/55 as I think they're two different features.

**Comment by bennet-esyoil** [comment]
I agree, repopulating the cache in the background is always a weird topic, especially when it comes to parallel requests and thus possibly multiple requests to regenerate a page. 

> I fear this might actually introduce more overhead than it would improve performance.

If you have a page that needs ~30 seconds to render due to external APIs it probably worth - but I agree, this should definitively be opt-in behavior so checking and updating only happens when opted in to reduce request time for non-stale-cache users.

If you have any idea on how to kickstart page-regeneration asynchronously I can start working on this.

**Comment by dulnan** [comment]
So I looked into this a bit more and there seems to be an experimental feature in Nitro called "tasks": https://nitro.unjs.io/guide/tasks It feels like this could be something that could help us here, at least for the "cron" part.

I have also refactored almost all code that relates to the route cache. It should now be much more reliable, as it now relies on Nitro/h3 hooks like `request` to serve from cache and `afterResponse` to store in cache. Previously I had to do some ugly hacks (overriding `node.res.end` for example) to make it work (and it didn't work very reliably). Should also make it much easier now to implement this feature.

> If you have a page that needs ~30 seconds to render due to external APIs it probably worth

Actually I had the same problem back in a Nuxt 2 app. But back then, using the old nuxt-multi-cache version, the data cache was always in-memory, so I was able to just store the promise of this absurdly long running request in cache and return that promise for every SSR request that needed it (because that API was also immediately overwhelmed with more than 3 requests at a time, fun times). Obviously I then had tens of SSR requests waiting, but at least they all waited for the same promise/fetch.

**Comment by wargt** [comment]
@dulnan I also need this feature. Since the page can be formed for 1 second, I would prefer to give the old version from the cache and then refresh the page in the background and put it in the cache.

Nuxt can do this, but it does not allow you to set a function for generating a key for caching. For example, consider the city cookie in the cache key.


```javascript
export default defineNuxtConfig({
  routeRules: {
    // Products page generated on demand, revalidates in background, cached until API response changes
    '/products': { swr: true },
    // Product page generated on demand, revalidates in background, cached for 1 hour (3600 seconds)
    '/products/**': { swr: 3600 },
  }
})
```

Can you help me please? Implement this functionality into your library. Give html from the cache and then revalidate in the background. Can you tell me when you plan to release the new version?

**Comment by dulnan** [comment]
@wargt Yes, "stale while revalidate" will be possible soon. The feature has already been implemented: https://github.com/dulnan/nuxt-multi-cache/pull/61 I hope to release it by end of this week.

Regarding the key: You would already be able to do that right now. The key is determined globally, using a method that you have to implement and that applies for any routes: https://nuxt-multi-cache.dulnan.net/features/route-cache#cache-key-for-routes To only vary by cookie for certain routes, you'd have to determine that based on `event.path`, because this module works slightly different than routeRules.

You can also provide a cache key prefix for all caches (data, route, component) at request time: https://nuxt-multi-cache.dulnan.net/overview/server-options#use-a-global-cache-prefix

**Comment by sathishzakapps** [comment]
@dulnan eagerly waiting for the stale if error and stale while revalidate options to be released... we loved this library and the missing part is already merged and verfied :) 

Please release this asap :) Thank you for this awesome library...

**Comment by wargt** [comment]
@dulnan We are really looking forward to the release

**Comment by dulnan** [comment]
Finally released it in 3.3.0, sorry for the long wait!

**Comment by wargt** [comment]
@dulnan Tell me how to use it. I didn't find it in the documentation. Thank you.

**Comment by dulnan** [comment]
Sure! Here you go: https://nuxt-multi-cache.dulnan.net/composables/useRouteCache#allowstalewhilerevalidate
The functionality is only enabled once you call `allowStaleWhileRevalidate()` in `useRouteCache()`. So it can be "enabled" on a route by route basis.

**Comment by wargt** [comment]
```vue
<template>
  <div>
    this is cache test page Yeasss!
    <br />
    {{ result }}
  </div>
</template>

<script setup lang="ts">
import { useAsyncData } from 'nuxt/app';

useRouteCache((helper) => {
  helper
    .setMaxAge(15)
    .setCacheable()
    .allowStaleWhileRevalidate()
    .setStaleIfError(15)
    .addTags(['page:test-cache']);
});

definePageMeta({
  layout: 'clean',
});

const result = await useAsyncData(() => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve('this data after timeout');
    }, 2000);
  });
});
</script>
```


this code is not worked - because i wait response 2 seconds every 15 seconds. 
I want to receive a response from the server quickly at all times. And the cache update should occur asynchronously in the background.

**Comment by dulnan** [comment]
There is currently no easy way to achieve that. Think of it this way: In order for the module to be able to store something in cache, it must hook into the life cycle of the request. There is a hook `afterResponse` provided by Nitro that is called _after_ the response has been sent to the client. So in order to regenerate the response, at least one request must go through the entire life cycle. If I were to return a stale response for that first request, I would end up just storing the stale response in cache again.

Nitro itself might be able to serve a stale response while regenerating in the background because the whole magic happens in `defineCachedEventHandler`. It is basically just caching the output of a single method, versus nuxt-multi-cache that has to operate on the entire request from start to finish.

The only solution currently would be to offer a `defineMultiCacheEventHandler()` server handler: Then it would be possible to basically replicate the Nitro behaviour in addition to offering features that Nitro is missing, such as cache tags.

However, that would only work for API routes. For Nuxt app rendering, there is no way (at least to my knowledge) to tell Nuxt/Nitro to use `defineMultiCacheEventHandler` when rendering a page. So you'd still have the same limitations as right now.

**Comment by dulnan** [comment]
btw I'm also not happy with the current implementation, I would really love to be able to provide a better solution here. But currently it's unfortunately not possible.

I hope that in the long term, Nitro and Nuxt will offer better ways for third party modules to implement such features without having to go through a lot of workarounds. And in the very long term, I hope that "the missing piece" that currently make it necessary to use nuxt-multi-cache's route cache, are available in Nitro itself and that this module only has to provide some features "on top", such as purge API, etc.

**Comment by wargt** [comment]
@dulnan Thanks for the detailed answer. Let's hope for the nuxt team
