### ISSUE TITLE
Route cache impossible to invalidate when using "unstorage/drivers/fs"

### ISSUE THREAD

**Issue by marconett** [dulnan/nuxt-multi-cache#79]
Given for example:

```js
import fsDriver from "unstorage/drivers/fs";

export default defineMultiCacheOptions({
  route: {
    storage: {
      driver: fsDriver({ base: "./.route-cache" }),
    },
  },
});
```

This breaks in the following line:

https://github.com/dulnan/nuxt-multi-cache/blob/a9068b369c0817dbf91f078cbc94bffb402a3cf1/src/runtime/server/api/purgeTags.ts#L99

The issue here is that `getItemRaw` on the storage driver returns a Buffer but `decodeRouteCacheItem` expects a String. So the line above always returns `undefined`.

This concrete issue could easily be mitigated by just using `getItem` here, but I am not 100% familiar with the source and this might need to get mitigated at other points as well.

I am using `unstorage/drivers/fs` successfully and without any issues with data cache, which does not use `getItemRaw`, but `getItem`. Is there a reason for this difference?

Thank you for open sourcing and maintaining this great library!

**Comment by dulnan** [comment]
It's for performance reasons: When using `getItem` and `setItem` unstorage will try to serialise it. What we store is just some metadata (which is JSON encoded) alongside the markup:

```
{"headers":{},"statusCode":200,"cacheTags":[],"staleWhileRevalidate":false}<CACHE_ITEM><html></html>
```

The `<CACHE_ITEM>` string is the delimiter, everything before that is metadata and afterwards is the cached markup.

Basically we can encode it ourselves without relying on unstorage for it. This is done for both the route cache and the component cache, since we know that this is always going to be a string.

For the data cache this is not possible, since it could be anything, so it makes sense to rely on unstorage to handle serialisation for us.

However, you are right that the code in the `purgeTags` event handler is broken as it does not call `handleRawCacheData()`. For some reason this variable here:

```typescript
const cached = await this.cacheContext?.[cacheName]?.getItemRaw(key)
```

is typed as `any` according to TS, which is why this bug could go unnoticed. I will fix this.
