### ISSUE TITLE
Exclude specific request headers from being cached

### ISSUE THREAD

**Issue by patrickkunzke** [dulnan/nuxt-multi-cache#88]
Hey! 

I am currently facing a problem where I activated the route cache. I have a composable which appends certain query params to all external links based on some request headers the app gets from a proxy that runs in front of it. Now I realized that after the page is cached these appended query params do not change at all, even if the headers do. Using `route.alterCachedHeaders` seems also not to work since logging them does not show the headers I expect.

Is there any way to exclude these headers from being cached that I am unaware of?

**Comment by dulnan** [comment]
If I understand the issue correctly, what you need to do is vary the cache key by the header using https://nuxt-multi-cache.dulnan.net/features/route-cache#cache-key-for-routes

In the string you return in this method you have to append the value of the header from your proxy. For example, when a request comes in with the header `x-your-proxy-header: foo` when `event.path === '/my-page'`, you would return:

```typescript
const header = getHeader(event, 'x-proxy-header')
return `${event.path}--proxy=${header}`
```

Resulting in a cache key `/my-page--proxy=foo`.

What this will do is store and serve multiple cache entries for the same page for each possible header value.

**Comment by patrickkunzke** [comment]
You are right, that would work, but I should have clarified that these headers represent query parameters and therefore this is not really viable. We are in a transition phase of an old system to the new one, in which the old acts as a proxy. It extracts relevant query params and adds a header for each of them. As long as we are in this transition phase, we have to support this functionality. 😕 

As far as I understand the source code here, serving the cached route happens during the nitro request hook, right? Do you think there might be a way to preserve the headers or pass them to the client if I used a separate nitro plugin?

**Comment by dulnan** [comment]
You are right that route cache is implemented via nitro hooks. When a request comes in, the module will call the `buildCacheKey` method to determine the exact cache key. When there is something in cache, it will serve it immediately. If there is nothing in the cache, it will continue the request. Once the request has been handled and is ready to be sent to the client, the module will first call `alterCachedHeaders` and then store the response together with the altered headers in the cache. The next request that results in the exact same cache key will be served the cached response, including the headers that have been stored along with the response body.

> Do you think there might be a way to preserve the headers or pass them to the client if I used a separate nitro plugin?

So this should already be the case - by default the module won't alter the headers, unless the `alterCachedHeaders` method adds/removes headers before its stored in cache. You should be able to receive all request headers in your app and also set your own response headers while an uncached response is handled. These will be part of the cache item.

**Comment by patrickkunzke** [comment]
But how can I deal with those ever-changing headers when serving a cached response? The route being completely cached is the outcome I want. Just not these proxy headers, so that I can append them to external links in the HTML based on the current request. I am also fine with handling this on the client, I just need a way to pass them to the client, even with a cached response. 

This might also be some kind of edge case and only a problem due to a lack of knowledge or understanding on my side. So every bit of help is highly appreciated! 🙏

**Comment by dulnan** [comment]
It depends how much these headers are changing. Even if you have let's say 30 possible header values, then it would still be reasonable to vary the cache key by these header values, assuming the amount of pages you have is below 100 or so. This would solve your problem entirely, because every header variation will store and serve different cache items, in which the response's HTML contains the correct query parameters in every generated link/URL.

However, I understand now (I think) that these proxy headers are not deterministic or that they can vary a lot, in which case you would just end up storing thousands of variations of the same page. In this case I agree, this would not be a valid solution.

Let's assume:
- You store only a single variant of every page in the cache
- You ignore any incoming proxy headers during SSR; all your generated links are **without** query params
- You append these query params on the client

The first problem you'll have: How do you pass these incoming headers to the client? Once your page is rendered on the server, what you receive in a nitro hook would be just the HTML. Of course, you could somehow string-replace/regex this data into the generated HTML, e.g. append `<script>window._PROXY_QUERY_PARAMS = { ... }</script>` into `<head>`. But the second problem is: When you then add these query parameters to all links on the client side during hydration you would end up with a lot of hydration errors everywhere. The generated HTML contains `<a href="/foobar">` but after hydration it will be `<a href="/foobar?proxyQuery=value">`, which leads to the errors (or more like warnings).

Now, this is not a problem specific with nuxt-multi-cache, but with caching in general; you'd face the same challenge with a classic cache such as Varnish or a CDN like Fastly/Cloudflare. Or if you were to use the built-in caching from Nitro.

One (bruteforce) way to solve the hydration issues would be to (in a nitro hook) alter the response HTML by manually appending the query parameters to every generated `<a>` tag. The "clean" way would be to parse the entire DOM, however this would obviously have quite the impact on performance, making the route cache probably useless.

A more efficient alternative to parsing the HTML could be that during SSR you append a known query param to every link, for example:

```vue
<NuxtLink :to="{ path: '/foobar', query: { __REPLACE_QUERY: 'REPLACE_QUERY' } }">
```

Resulting in `<a href="/foobar?__REPLACE_QUERY=REPLACE_QUERY">`. You could then do a simple string replace of this specific string in the generated HTML which should be much more performant. But this could potentially break other things, when this string appears in a JSON-encoded payload from Nuxt for example.

All of that would be possible, using a custom Nitro plugin and hooking into the `beforeResponse` event.

But, maybe it's worth asking: Do you actually need the route cache after all? You can implement caching on several other levels using this module. If you need to do slow API requests on the server the [data cache](https://nuxt-multi-cache.dulnan.net/features/data-cache) might be useful to cache such API responses. If you have complex components, you could cache them with the [component cache](https://nuxt-multi-cache.dulnan.net/features/component-cache) (but if they also render links that need query params you'd have the same problem again). Nuxt rendering is quite fast, even with complex pages and components.

**Comment by patrickkunzke** [comment]
Wow, thank you so much for your answer! I played around with it a bit more yesterday, and in the end went with what you rightfully questioned: Do I even need the route cache? 

Turns out (for now) I don't and the data cache already speeds up everything significantly. I still think the route cache is something I would like to use in the future, since the pages of our product can contain quite a lot of content, but for that I have to see how our system develops. 😄 

Again, thanks for your help! 🙂
